import {cardLocalImages} from '../../public/Assets/images/imagesContrller'
import {v4 as uuidv4} from 'uuid'

export const newProducts = [
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product1,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product2,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product3,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product4,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product5,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product6,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product7,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product8,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product9,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: true,
        slug: uuidv4(),
        inCart: false,
    },
]

export const similarProducts = [
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product1,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product2,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product3,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product4,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product5,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product6,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product7,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product8,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product9,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product1,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product2,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product3,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product4,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product5,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product6,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product7,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product8,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product9,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product1,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product2,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product3,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product4,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product5,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product6,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product7,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product8,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    },
    {
        id: uuidv4(),
        name: 'Flower name',
        photo: cardLocalImages.product9,
        price: 12.99,
        lastPrice: 15.99,
        discount: 20,
        isNew: false,
        slug: uuidv4(),
        inCart: false,
    }
]