import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Loading from "../Components/Common/Loading/loading";
import List from "../Components/List/list";
import Footer from "../Components/Footer/footer";
import Header from "../Components/Header/header";
import {useSelector} from "react-redux";

export default function Home() {
    const loading = useSelector(state => state?.commonReducer.loading)
    if (loading) {
       return  <Loading />
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Flowers shop</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel='icon' href='/favicon.ico' />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>
            </Head>
                <Header />
            <main className={styles.main}>
                <List />
            </main>

            <footer className={styles.footer}>
               <Footer />
            </footer>
        </div>
    )
}
